import Demo from "../../../assets/images/responses/demo.jpg";

export const TableData = [
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Female",
      name3: "White or Caucasian",
      name4:"I regularly eat meat and fish",
      name5:"I eat it at least once a month",
      name6:"Beyond MeatImpossible FoodsLightlife Foods & Field Roast Morningstar Farms, Gardein Sweet Earth",
      name7:"I cook them at home",
      name8:"Strongly Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:22,
      number:1
    },
    {
      icon: Demo,
      name: "25-Jan-2021, 06:35",
      name2: "Female",
      name3: "Asian",
      name4:"I strictly follow a vegetarian diet",
      name5:"I eat it at least once a week or more often",
      name6:"Lightlife Foods & Field Roast",
      name7:"I order them at fast food restaurants",
      name8:"	Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:21,
      number:2
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Male",
      name3: "White or Caucasian",
      name4:"I regularly eat meat and fish",
      name5:"I’ve never had plant based meats before",
      name6:"Morningstar Farms",
      name7:"I order them at fast food restaurants",
      name8:"Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:20,
      number:3
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Male",
      name3: "Prefer not to say",
      name4:"I mostly follow a vegetarian based diet but will occasionally eat meat and fish",
      name5:"I eat it at least once a month",
      name6:"Other",
      name7:"I cook them at home",
      name8:"Neither Agree nor Disagree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:23,
      number:4
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Female",
      name3: "Asian",
      name4:"I mostly follow a vegetarian based diet",
      name5:"I eat it at least once a month",
      name6:"Lightlife Foods & Field Roast",
      name7:"I order them at dine-in restaurants",
      name8:"Strongly Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:19,
      number:5
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Female",
      name3: "Prefer not to say",
      name4:"I regularly eat meat and fish",
      name5:"I eat it at least once a week or more often",
      name6:"Beyond MeatImpossible Foods",
      name7:"I cook them at home",
      name8:"Neither Agree nor Disagree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:22,
      number:6
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Female",
      name3: "White or Caucasian",
      name4:"I regularly eat meat and fish",
      name5:"I’ve never had plant based meats before",
      name6:"Beyond MeatImpossible FoodsMorningstar Farms, Tofurky Gardein",
      name7:"I order them at dine-in restaurants",
      name8:"Not Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:21,
      number:7
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Male",
      name3: "Asian",
      name4:"I regularly eat Vegetarian",
      name5:"I eat it at least once a month",
      name6:"Morningstar Farms, Tofurky",
      name7:"I cook them at home",
      name8:"Strongly Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:25,
      number:8
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Male",
      name3: "Prefer not to say",
      name4:"I regularly eat fish",
      name5:"I eat it at least once a month",
      name6:"Impossible Foods",
      name7:"I order them at dine-in restaurants",
      name8:"Disagree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:26,
      number:9
    },
    {
      icon: Demo,
      name: "22-Jan-2021, 09:31",
      name2: "Female",
      name3: "White or Caucasian",
      name4:"I mostly follow a vegetarian based diet but will occasionally eat meat and fish",
      name5:"I eat it at least once a week or more often",
      name6:"Impossible FoodsMorningstar Farms, Gardein",
      name7:"I order them at dine-in restaurantsI order them at fast food restaurants",
      name8:"Agree",
      isChecked: true,
      isFavourite: true,
      videoTitle: "Video title comes here...",
      videoSize: "12 MB",
      videoDuration: "3 m 57 s",
      age:20,
      number:10
    },
  ];
  
  export  const columns = [
    {
      questionName:
        "Date-time",
        key:1
    },
    { questionName: "Gender" ,
    key:2},
    { questionName: "Ethnicity",
    key:'name' },
    { questionName: "Age",
    key:3 },
    { questionName: "Q6.How would you describe your eating habits?",
    key:'name' },
    { questionName: "Q7.How often do you consume plant-based meats (Impossible Burgers, Beyond Meat, Morningstar,etc.)?" ,
    key:2},
    { questionName: "Q8.Please select all the plant-based meat brands you’ve tried:",
    key:3 },
    { questionName: "Q11.Where do you typically eat plant based meats? (select all that apply)",
    key:'name' },
    { questionName: "Q13.Evaluate the following statement: I am more likely to eat at a restaurant if they offer plant-based meats on their menu.",
    key:'name' },
  ];